### ISSUE TITLE
sql importer

### ISSUE THREAD

**Issue by joshcarp** [anz-bank/sysl#883] opened 2020-06-12 00:12 UTC
the current Sysl version Doesn't support importing sql
It'd be nice to have a spanner flavoured sql importer so that importers don't need to be manually translated into sysl table statements

**Comment by andrewemeryanz** [comment] 2020-07-23 05:14
Duplicate of: https://github.com/anzx/acceleration/issues/326

**Closed by andrewemeryanz** 2020-07-23 05:14 UTC
Labels: P0, enhancement
